name: explore-siphon
channels:
- conda-forge
dependencies:
- bokeh=3.2
- cfgrib
- eccodes
- dask>=2023.4.0
- dask-jobqueue>=0.8.1
- distributed
- intake>=0.6.8
- intake-esm>=2020.8.15
- ipykernel
- matplotlib
- pip
- python>=3.8
- s3fs
- siphon
- tqdm
- watermark
- xarray>=2023.4.2
## If you are not running on a pre-installed jupyter instance, uncomment this:
#- jupyterlab
